### ISSUE TITLE
[FEATURE REQUEST] Save/load .spark.json

### ISSUE THREAD

**Issue by RuggeroVisintin** [RuggeroVisintin/spark-engine-web-editor#25]
**Is your feature request related to a problem? Please describe.**
Scenes cannot be saved and loaded from the disk

**Describe the experience you'd like**
Be able to save the scene to disk and load a scene from a scene file

**Describe alternatives you've considered**
Use FileSystem API to let the user select the scene file to load

**Additional context**
Relates to: https://github.com/RuggeroVisintin/SparkEngineWeb/issues/283
Blocked By: https://github.com/RuggeroVisintin/SparkEngineWeb/issues/323
Blocked By: https://github.com/RuggeroVisintin/SparkEngineWeb/issues/348
Blocked By: https://github.com/RuggeroVisintin/SparkEngineWeb/issues/376

**Tasks**

- [x] Add file menu
- [x] Save to file
- [x] Load from file

**Comment by RuggeroVisintin** [comment]
The loading mechanism for plane JSON files should be implemented in the editor as it does not re-use the same mechanism that the engine uses at runtime.

This can be implemented through the usage of [FileSystemAPI](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API)
